config/routes.rb
Medellin::Application.routes.draw do

  resources :periods, only: [:show]

  root :to => 'static#index'

  controller :static do
    get "now"
    get "future"
  end

  get "ajax/tweets"
  get "ajax/mentions"

  
  devise_for :admin_users

  get 'admin' => "admin#dashboard", as: :admin_user_root

  namespace :admin do
    resources :nodes
    resources :admin_users
    resources :categories
    resources :periods
    post 'upload' => 'nodes#upload', as: :import_nodes
  end
end

app/views/admin/header/_inbox.html.erb
<!-- BEGIN INBOX DROPDOWN -->
<li class="dropdown" id="header_inbox_bar">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
	<i class="fa fa-envelope"></i>
	<span class="badge">
		5
	</span>
	</a>
	<ul class="dropdown-menu extended inbox">
		<li>
			<p>
				You have 12 new messages
			</p>
		</li>
		<li>
			<ul class="dropdown-menu-list scroller" style="height: 250px;">
				<li>
					<a href="inbox.html?a=view">
					<span class="photo">
						<img src="./assets/img/avatar2.jpg" alt=""/>
					</span>
					<span class="subject">
						<span class="from">
							Lisa Wong
						</span>
						<span class="time">
							Just Now
						</span>
					</span>
					<span class="message">
						 Vivamus sed auctor nibh congue nibh. auctor nibh auctor nibh...
					</span>
					</a>
				</li>
				<li>
					<a href="inbox.html?a=view">
					<span class="photo">
						<img src="./assets/img/avatar3.jpg" alt=""/>
					</span>
					<span class="subject">
						<span class="from">
							Richard Doe
						</span>
						<span class="time">
							16 mins
						</span>
					</span>
					<span class="message">
						 Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh...
					</span>
					</a>
				</li>
				<li>
					<a href="inbox.html?a=view">
					<span class="photo">
						<img src="./assets/img/avatar1.jpg" alt=""/>
					</span>
					<span class="subject">
						<span class="from">
							Bob Nilson
						</span>
						<span class="time">
							2 hrs
						</span>
					</span>
					<span class="message">
						 Vivamus sed nibh auctor nibh congue nibh. auctor nibh auctor nibh...
					</span>
					</a>
				</li>
				<li>
					<a href="inbox.html?a=view">
					<span class="photo">
						<img src="./assets/img/avatar2.jpg" alt=""/>
					</span>
					<span class="subject">
						<span class="from">
							Lisa Wong
						</span>
						<span class="time">
							40 mins
						</span>
					</span>
					<span class="message">
						 Vivamus sed auctor 40% nibh congue nibh...
					</span>
					</a>
				</li>
				<li>
					<a href="inbox.html?a=view">
					<span class="photo">
						<img src="./assets/img/avatar3.jpg" alt=""/>
					</span>
					<span class="subject">
						<span class="from">
							Richard Doe
						</span>
						<span class="time">
							46 mins
						</span>
					</span>
					<span class="message">
						 Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh...
					</span>
					</a>
				</li>
			</ul>
		</li>
		<li class="external">
			<a href="inbox.html">See all messages <i class="m-icon-swapright"></i></a>
		</li>
	</ul>
</li>
<!-- END INBOX DROPDOWN -->

app/views/admin/header/_notification.html.erb
<!-- BEGIN NOTIFICATION DROPDOWN -->
<li class="dropdown" id="header_notification_bar">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
	<i class="fa fa-warning"></i>
	<span class="badge">
		6
	</span>
	</a>
	<ul class="dropdown-menu extended notification">
		<li>
			<p>
				You have 14 new notifications
			</p>
		</li>
		<li>
			<ul class="dropdown-menu-list scroller" style="height: 250px;">
				<li>
					<a href="#">
					<span class="label label-sm label-icon label-success">
						<i class="fa fa-plus"></i>
					</span>
					 New user registered.
					<span class="time">
						Just now
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="label label-sm label-icon label-danger">
						<i class="fa fa-bolt"></i>
					</span>
					 Server #12 overloaded.
					<span class="time">
						15 mins
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="label label-sm label-icon label-warning">
						<i class="fa fa-bell-o"></i>
					</span>
					 Server #2 not responding.
					<span class="time">
						22 mins
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="label label-sm label-icon label-info">
						<i class="fa fa-bullhorn"></i>
					</span>
					 Application error.
					<span class="time">
						40 mins
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="label label-sm label-icon label-danger">
						<i class="fa fa-bolt"></i>
					</span>
					 Database overloaded 68%.
					<span class="time">
						2 hrs
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="label label-sm label-icon label-danger">
						<i class="fa fa-bolt"></i>
					</span>
					 2 user IP blocked.
					<span class="time">
						5 hrs
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="label label-sm label-icon label-warning">
						<i class="fa fa-bell-o"></i>
					</span>
					 Storage Server #4 not responding.
					<span class="time">
						45 mins
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="label label-sm label-icon label-info">
						<i class="fa fa-bullhorn"></i>
					</span>
					 System Error.
					<span class="time">
						55 mins
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="label label-sm label-icon label-danger">
						<i class="fa fa-bolt"></i>
					</span>
					 Database overloaded 68%.
					<span class="time">
						2 hrs
					</span>
					</a>
				</li>
			</ul>
		</li>
		<li class="external">
			<a href="#">See all notifications <i class="m-icon-swapright"></i></a>
		</li>
	</ul>
</li>
<!-- END NOTIFICATION DROPDOWN -->

app/views/admin/header/_todo.html.erb
<!-- BEGIN TODO DROPDOWN -->
<li class="dropdown" id="header_task_bar">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
	<i class="fa fa-tasks"></i>
	<span class="badge">
		5
	</span>
	</a>
	<ul class="dropdown-menu extended tasks">
		<li>
			<p>
				You have 12 pending tasks
			</p>
		</li>
		<li>
			<ul class="dropdown-menu-list scroller" style="height: 250px;">
				<li>
					<a href="#">
					<span class="task">
						<span class="desc">
							New release v1.2
						</span>
						<span class="percent">
							30%
						</span>
					</span>
					<span class="progress">
						<span style="width: 40%;" class="progress-bar progress-bar-success" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100">
							<span class="sr-only">
								40% Complete
							</span>
						</span>
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="task">
						<span class="desc">
							Application deployment
						</span>
						<span class="percent">
							65%
						</span>
					</span>
					<span class="progress progress-striped">
						<span style="width: 65%;" class="progress-bar progress-bar-danger" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100">
							<span class="sr-only">
								65% Complete
							</span>
						</span>
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="task">
						<span class="desc">
							Mobile app release
						</span>
						<span class="percent">
							98%
						</span>
					</span>
					<span class="progress">
						<span style="width: 98%;" class="progress-bar progress-bar-success" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100">
							<span class="sr-only">
								98% Complete
							</span>
						</span>
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="task">
						<span class="desc">
							Database migration
						</span>
						<span class="percent">
							10%
						</span>
					</span>
					<span class="progress progress-striped">
						<span style="width: 10%;" class="progress-bar progress-bar-warning" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">
							<span class="sr-only">
								10% Complete
							</span>
						</span>
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="task">
						<span class="desc">
							Web server upgrade
						</span>
						<span class="percent">
							58%
						</span>
					</span>
					<span class="progress progress-striped">
						<span style="width: 58%;" class="progress-bar progress-bar-info" aria-valuenow="58" aria-valuemin="0" aria-valuemax="100">
							<span class="sr-only">
								58% Complete
							</span>
						</span>
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="task">
						<span class="desc">
							Mobile development
						</span>
						<span class="percent">
							85%
						</span>
					</span>
					<span class="progress progress-striped">
						<span style="width: 85%;" class="progress-bar progress-bar-success" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100">
							<span class="sr-only">
								85% Complete
							</span>
						</span>
					</span>
					</a>
				</li>
				<li>
					<a href="#">
					<span class="task">
						<span class="desc">
							New UI release
						</span>
						<span class="percent">
							18%
						</span>
					</span>
					<span class="progress progress-striped">
						<span style="width: 18%;" class="progress-bar progress-bar-important" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100">
							<span class="sr-only">
								18% Complete
							</span>
						</span>
					</span>
					</a>
				</li>
			</ul>
		</li>
		<li class="external">
			<a href="#">See all tasks <i class="m-icon-swapright"></i></a>
		</li>
	</ul>
</li>
<!-- END TODO DROPDOWN -->

app/views/admin/header/_user_login.html.erb
<!-- BEGIN USER LOGIN DROPDOWN -->
<li class="dropdown user">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
	<!-- <img alt="" src="/assets/img/avatar1_small.jpg"/> -->
	<span class="username">
		<%= current_admin_user.email %>
	</span>
	<i class="fa fa-angle-down"></i>
	</a>
	<ul class="dropdown-menu">
		<!-- <li>
			<a href="extra_profile.html"><i class="fa fa-user"></i> My Profile</a>
		</li>
		<li>
			<a href="page_calendar.html"><i class="fa fa-calendar"></i> My Calendar</a>
		</li>
		<li>
			<a href="inbox.html"><i class="fa fa-envelope"></i> My Inbox
			<span class="badge badge-danger">
				3
			</span>
			</a>
		</li>
		<li>
			<a href="#"><i class="fa fa-tasks"></i> My Tasks
			<span class="badge badge-success">
				7
			</span>
			</a>
		</li>
		<li class="divider">
		</li>
		<li>
			<a href="javascript:;" id="trigger_fullscreen"><i class="fa fa-move"></i> Full Screen</a>
		</li>
		<li>
			<a href="extra_lock.html"><i class="fa fa-lock"></i> Lock Screen</a>
		</li> -->
		<li>
			<%= link_to destroy_admin_user_session_path, method: :delete do %>
				<i class="fa fa-key"></i> Log Out
			<% end %>
		</li>
	</ul>
</li>
<!-- END USER LOGIN DROPDOWN -->